# Configuration file for Strands Location Service Weather
# This file contains default settings that work for most users
# Create config.local.toml or use environment variables to override specific values

[opentelemetry]
service_name = "strands-location-service-weather"

[bedrock]
model_id = "anthropic.claude-3-sonnet-20240229-v1:0"
region_name = "us-east-1"

[weather_api]
base_url = "https://api.weather.gov"
user_agent_weather = "LocationWeatherService/1.0"
user_agent_alerts = "LocationWeatherAlertsService/1.0"
timeout = 10

[mcp]
command = "uvx"
server_package = "awslabs.aws-location-mcp-server@latest"

[ui]
app_title = "PlaceFinder & Weather"
welcome_message = "Ask about locations, routes, nearby places, or weather conditions."
prompt_text = "How can I help you? "

[deployment]
mode = "local"  # Options: "local", "mcp", "agentcore"
bedrock_model_id = "anthropic.claude-3-sonnet-20240229-v1:0"
aws_region = "us-east-1"
enable_tracing = true
timeout = 30
# agentcore_agent_id = ""  # Required when mode = "agentcore"

[agentcore]
# agent_id = ""  # Set via AGENTCORE_AGENT_ID environment variable
agent_alias_id = "TSTALIASID"
# session_id = ""  # Optional session ID for AgentCore
enable_trace = true

[guardrail]
# guardrail_id = ""  # Optional Bedrock Guardrail ID
guardrail_version = "DRAFT"
enable_content_filtering = true
enable_pii_detection = true
enable_toxicity_detection = true