name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quick-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Code formatting check
      run: |
        uv run black --check --diff .

    - name: Linting check
      run: |
        uv run ruff check .

    - name: Fast tests only (for quick feedback)
      run: |
        uv run pytest -m "not slow" --tb=short

  performance-check:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'performance')
    steps:
    - uses: checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Run performance tests
      run: |
        uv run pytest tests/test_performance.py -v

  comment-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Run tests with coverage
      run: |
        uv run pytest --cov=src --cov-report=term-missing --cov-report=json

    - name: Coverage comment
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ github.token }}
        MINIMUM_GREEN: 60
        MINIMUM_ORANGE: 50